# Generated by Django 5.2.16 on 2026-07-27 04:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(help_text='ISBN-10 or ISBN-13, digits only.', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must be a valid ISBN-10 or ISBN-13 (digits only, optional trailing X).', regex='^(?:\\d{9}[\\dX]|\\d{13})$')])),
                ('published_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
